### ISSUE TITLE
Titles <= Stage 3 Displayed as Champion Names

### ISSUE THREAD

**Issue by karlhorky** [bevacqua/prop-tc39#10]
Looks like proposals Stage 3 and lower are being given titles of the champion's names instead of the proposal name:

<img width="566" alt="screen shot 2019-03-05 at 10 13 43" src="https://user-images.githubusercontent.com/1935696/53794107-922dd200-3f2f-11e9-9dd7-08bd2908edf5.png">

**Comment by hemanth** [comment]
Fixed in #11

**Comment by karlhorky** [comment]
Hm, has #11 been deployed already? The issue is still present on https://prop-tc39.now.sh/

**Comment by hemanth** [comment]
//cc @bevacqua

**Comment by MartinMuzatko** [comment]
Please deploy :<
